### ISSUE TITLE
Lo Fi / Hi Fi Option Like Mic'd Up

### ISSUE THREAD

**Issue by TonyTimee** [DEMOLITIONDON96/Demolition-Engine#110]
### **LOFI / HIFI OPTION**

**Maybe An Option Where it would play a chart depending on the mode**

**EX:**
![ezgif-4-504d7e57f9](https://user-images.githubusercontent.com/88756260/171786000-129f9ca2-9180-4ccf-9dfb-d0fc1329bfc9.gif)

**Modder's can delete the option if they don't want to add it in**
**I think it will be cooler*

### To test your sight, and reliability, please select the option of what should NOT be requested.

A good idea

**Comment by PrismLight** [comment]
Do you have this as a fork or on ur computer lol.

**Comment by Theoyeah** [comment]
hehe 
![image](https://user-images.githubusercontent.com/97792861/171996830-823b2b41-27ae-4763-8ab1-1f2ff4f59387.png)

**Comment by DEMOLITIONDON96** [comment]
@TonyTimee you have access to this repo, go right ahead lol

**Comment by Theoyeah** [comment]
> @TonyTimee you have access to this repo, go right ahead lol

He have acces to this repo  for ages, he just don't know how to pr

**Comment by PrismLight** [comment]
Make a repo with all of this and we can add it do Demolition Engine. We don't need a pr.

**Comment by TonyTimee** [comment]
> @TonyTimee you have access to this repo, go right ahead lol

I can do the redesign menu is that idk how we can do the Lo Fi / Hi Fi

**Comment by DeceptedPar** [comment]
I dont think this should be a thing in the setting but I think it should be a thing in freeplay when you press control and that menu pops up

**Comment by PrismLight** [comment]
Show us the source to add it ~~Matt~~ Tony.
