### ISSUE TITLE
Broken shaders

### ISSUE THREAD

**Issue by te-agma-at** [DEMOLITIONDON96/Demolition-Engine#113]
### Describe your bug here.

Here's the code:
`function onCreatePost()
    addEffect1('camGame', 0.00500);
    addEffect1('hud', 0.00500);
    addEffect1('other', 0.00500);
    addEffect4('camGame', 0.3);
    addEffect4('hud', 0.3);
    addEffect4('other', 0.3);
end`

And here is what it outputs when i try to run the game using the code above:
![image](https://user-images.githubusercontent.com/72958435/173475009-460dafde-6c3d-4142-8253-83d1daac36a0.png)

Is this a bug or a code error? And how do i fix this issue if it's an error? Thanks!

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I edited the song Monster with the script above

**Comment by TonyTimee** [comment]
Hmmmm im not sure,
none of the team got that error before (i think so)
try re writting it and make sure their isnt anything mispelled
