### ISSUE TITLE
Shaders Lua not working

### ISSUE THREAD

**Issue by STIk-3807** [DEMOLITIONDON96/Demolition-Engine#116]
### Describe your problem here.

i tried using a shader lua for the engine and it doesnt show it, nothing is wrong with my graphics card i have a 3060ti i think im just stupid or the shaders are a bit broken

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

**Comment by TonyTimee** [comment]
can i see code and a image to see the problem?

**Comment by STIk-3807** [comment]
this is the error for the shaders:

source/FunkinLua.hx:82: lua file loaded succesfully:mods/scripts/shaders.lua
llua/Convert.hx:103: return value not supported
2

shaders lua:

function onCreatePost()

    addVCREffect('camgame')
    addVCREffect('camhud', true)
end

**Comment by STIk-3807** [comment]
also how do you remove the blue glow in the menu?

**Comment by DEMOLITIONDON96** [comment]
> also how do you remove the blue glow in the menu? On Sun, Jun 19, 2022 at 6:08 PM STIk ***@***.***> wrote:

go to TitleState.hx and find "gradientBar" i think

**Comment by TonyTimee** [comment]
> 

for now

its used like this

```lua
function onCreatePost()
    addEffect5('camgame')
    addEffect5('camhud', true)
end
```

once we release 0.2.4 you can use this, or a action build

```lua
function onCreatePost()
    addVCREffect('camgame')
    addVCREffect('camhud', true)
end
```
