### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by SonicProYT** [DEMOLITIONDON96/Demolition-Engine#48]
### Describe your bug here.

i cant compile demolition engine rn

### Command Prompt/Terminal logs (if existing)

```bash
source/TitleState.hx:391: characters 15-27 : flixel.FlxSprite has no field screencanter (Suggestion: screenCenter)
source/TitleState.hx:615: characters 18-36 : Array<String> should be String
source/TitleState.hx:615: characters 18-36 : ... For function argument 'text'
source/TitleState.hx:616: characters 6-24 : Bool should be flixel.FlxSprite
source/TitleState.hx:621: characters 6-25 : Bool should be flixel.FlxSprite
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

sprites, songs, and data folders

**Comment by DEMOLITIONDON96** [comment]
Oh yeah, this is the image that it’s suppose to use, but it’s not in the files yet, just remove it lol

**Comment by DEMOLITIONDON96** [comment]
If anything, just go back to the commit before the changes made to TitleState.hx

**Comment by Theoyeah** [comment]
@DEMOLITIONDON96 it is fixed ?
