### ISSUE TITLE
mainmenustate doesn’t contain “changeItem” identifier

### ISSUE THREAD

**Issue by SonicProYT** [DEMOLITIONDON96/Demolition-Engine#77]
### Describe your bug here.

i was gonna compile my mod that uses this engine but 
the main menu state doesn’t have a identifier named “changeItem”

### Command Prompt/Terminal logs (if existing)

_source/MainMenuState.hx:156: characters 7-17 : Unknown identifier : changeItem_

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

the stuff i put for my mod that uses this engine, won’t tell what the stuff is yet

**Comment by DEMOLITIONDON96** [comment]
idk if it's fixed or not, but it was because the changeItem function wasn't included in the code for some reason, even thought the menu relies on it a lot lol

**Comment by SonicProYT** [comment]
oh

ok time to close it
