### ISSUE TITLE
source/PlayState.hx:5360: characters 4-58 : String should be Array<Dynamic>

### ISSUE THREAD

**Issue by SonicProYT** [DEMOLITIONDON96/Demolition-Engine#88]
### Describe your bug here.

cant compile for some reason, cuz of the ratings code being array<dynamic>, but happens to actually be a string

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:5360: characters 4-58 : String should be Array<Dynamic>
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Sprites, some haxe files, charts, songs, etc.

**Comment by DEMOLITIONDON96** [comment]
@TonyTimee can you take a look at this? I don’t have my laptop for the next 3 weeks lmao

**Comment by PrismLight** [comment]
> @TonyTimee can you take a look at this? I don’t have my laptop for the next 3 weeks lmao

It's formatting.

**Comment by SonicProYT** [comment]
> > @TonyTimee can you take a look at this? I don’t have my laptop for the next 3 weeks lmao
> 
> It's formatting.

Formatting is kinda useless but, sure, agreed.

**Comment by DEMOLITIONDON96** [comment]
Then again, I don’t understand how this isn’t working if i was just using this exact code for a mod I’m working on and it works fine

**Comment by SonicProYT** [comment]
> > @TonyTimee can you take a look at this? I don’t have my laptop for the next 3 weeks lmao
> 
> It's formatting.

i tried that and nothing.
source/PlayState.hx:5360: characters 5-59 : String should be Array<Dynamic>

**Comment by SonicProYT** [comment]
nvm it worked
i just have to put it like this
![image](https://user-images.githubusercontent.com/62410083/166501641-6e0ae485-bb02-464f-acf9-a711cb8ebad1.png)

**Comment by DEMOLITIONDON96** [comment]
> nvm it worked i just have to put it like this ![image](https://user-images.githubusercontent.com/62410083/166501641-6e0ae485-bb02-464f-acf9-a711cb8ebad1.png)

oh, glad it got resolved then
