### ISSUE TITLE
Bro, you fucked the entire menu screeen

### ISSUE THREAD

**Issue by Theoyeah** [DEMOLITIONDON96/Demolition-Engine#95]
### Describe your bug here.

![image](https://user-images.githubusercontent.com/97792861/167246936-a06c060d-8f07-4b7d-ab03-a4a3b814e222.png)
WTF ???
And some buttons like options won't work

### Command Prompt/Terminal logs (if existing)

```bash
? 

No
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No, just re-compiled cuz my pc reseted 5 days ago

**Comment by DEMOLITIONDON96** [comment]
No shit, I saw this 3 fucking days ago lmao, that’s because there’s more than 4 options, idk why it does that, still trying to find a way to have all the options there without having the god damn menu breaking and shit
